# Generated by Django 4.2.18 on 2025-01-25 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CrewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeetupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeetupSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeetupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
                ('work_in_progress', models.BooleanField(default=False)),
                ('max_minutes', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrgPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=48)),
                ('first_name', models.CharField(max_length=48)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrereqDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrereqSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_numerator', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('org', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.org')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeetupSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('meetup_spot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetupspot')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('meetup_template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetuptemplate')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_count', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('crew_template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.crewtemplate')),
            ],
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['deleted', 'name'], name='api_subject_deleted_5cea12_idx'),
        ),
        migrations.AddIndex(
            model_name='spottype',
            index=models.Index(fields=['deleted', 'name'], name='spot_type_idx'),
        ),
        migrations.AddField(
            model_name='signup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signup',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.crew'),
        ),
        migrations.AddField(
            model_name='signup',
            name='meetup_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetuprole'),
        ),
        migrations.AddField(
            model_name='signup',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person'),
        ),
        migrations.AddField(
            model_name='prereqset',
            name='required_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetuptemplate'),
        ),
        migrations.AddField(
            model_name='prereqdetail',
            name='prereq_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.prereqset'),
        ),
        migrations.AddField(
            model_name='prereqdetail',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetuptemplate'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgperson',
            name='org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.org'),
        ),
        migrations.AddField(
            model_name='orgperson',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.person'),
        ),
        migrations.AddIndex(
            model_name='org',
            index=models.Index(fields=['deleted', 'name'], name='org_idx'),
        ),
        migrations.AddField(
            model_name='meetuptemplate',
            name='crew_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.crewtemplate'),
        ),
        migrations.AddField(
            model_name='meetuptemplate',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.facility'),
        ),
        migrations.AddField(
            model_name='meetuptemplate',
            name='meetup_spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetupspot'),
        ),
        migrations.AddField(
            model_name='meetuptemplate',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.org'),
        ),
        migrations.AddField(
            model_name='meetuptemplate',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.subject'),
        ),
        migrations.AddField(
            model_name='meetupspot',
            name='facility',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.facility'),
        ),
        migrations.AddField(
            model_name='meetupspot',
            name='spot_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.spottype'),
        ),
        migrations.AddIndex(
            model_name='meetuprole',
            index=models.Index(fields=['deleted', 'name'], name='api_meetupr_deleted_814e7c_idx'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.crew'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.facility'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='meetup_spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetupspot'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='meetup_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetuptemplate'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.org'),
        ),
        migrations.AddIndex(
            model_name='focus',
            index=models.Index(fields=['deleted', 'name'], name='api_focus_deleted_35f906_idx'),
        ),
        migrations.AddField(
            model_name='facility',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.org'),
        ),
        migrations.AddIndex(
            model_name='crewtemplate',
            index=models.Index(fields=['name', 'deleted'], name='api_crewtem_name_95e4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='crew',
            index=models.Index(fields=['name', 'deleted'], name='api_crew_name_acfd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['deleted', 'user_id', 'name'], name='user_preference_idx'),
        ),
        migrations.AddIndex(
            model_name='userperson',
            index=models.Index(fields=['deleted', 'user_id', 'person_id'], name='user_person_idx'),
        ),
        migrations.AddIndex(
            model_name='userorg',
            index=models.Index(fields=['deleted', 'user_id', 'org_id'], name='user_org_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeetupspot',
            index=models.Index(fields=['deleted', 'user_id', 'meetup_spot_id'], name='user_meetup_spot_idx'),
        ),
        migrations.AddIndex(
            model_name='topicresource',
            index=models.Index(fields=['deleted', 'description'], name='api_topicre_deleted_e96700_idx'),
        ),
        migrations.AddIndex(
            model_name='topicresource',
            index=models.Index(fields=['deleted', 'topic_id'], name='api_topicre_deleted_f51f99_idx'),
        ),
        migrations.AddIndex(
            model_name='topicresource',
            index=models.Index(fields=['deleted', 'topic_id', 'description'], name='api_topicre_deleted_41f886_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['deleted', 'name'], name='api_topic_deleted_b7e4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['deleted', 'subject_id'], name='api_topic_deleted_bb2506_idx'),
        ),
        migrations.AddIndex(
            model_name='templatetopic',
            index=models.Index(fields=['meetup_template_id', 'deleted'], name='api_templat_meetup__dcfe07_idx'),
        ),
        migrations.AddIndex(
            model_name='templatetopic',
            index=models.Index(fields=['topic_id', 'deleted'], name='api_templat_topic_i_8f7146_idx'),
        ),
        migrations.AddIndex(
            model_name='templatetopic',
            index=models.Index(fields=['meetup_template_id', 'topic_id', 'deleted'], name='api_templat_meetup__7cc831_idx'),
        ),
        migrations.AddIndex(
            model_name='templatetopic',
            index=models.Index(fields=['topic_id'], name='api_templat_topic_i_a403d9_idx'),
        ),
        migrations.AddIndex(
            model_name='templatetopic',
            index=models.Index(fields=['meetup_template_id'], name='api_templat_meetup__2d17e1_idx'),
        ),
        migrations.AddIndex(
            model_name='templaterole',
            index=models.Index(fields=['crew_template_id', 'deleted'], name='api_templat_crew_te_f196e1_idx'),
        ),
        migrations.AddIndex(
            model_name='templaterole',
            index=models.Index(fields=['name', 'deleted'], name='api_templat_name_ab4bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='signup',
            index=models.Index(fields=['person_id'], name='api_signup_person__02990f_idx'),
        ),
        migrations.AddIndex(
            model_name='signup',
            index=models.Index(fields=['crew_id'], name='api_signup_crew_id_4f31e4_idx'),
        ),
        migrations.AddIndex(
            model_name='signup',
            index=models.Index(fields=['meetup_role_id'], name='api_signup_meetup__df7f32_idx'),
        ),
        migrations.AddIndex(
            model_name='signup',
            index=models.Index(fields=['created_at'], name='api_signup_created_3b0745_idx'),
        ),
        migrations.AddIndex(
            model_name='signup',
            index=models.Index(fields=['deleted'], name='api_signup_deleted_6c2376_idx'),
        ),
        migrations.AddIndex(
            model_name='signup',
            index=models.Index(fields=['created_by'], name='api_signup_created_604e78_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['deleted', 'last_name', 'first_name'], name='person_idx'),
        ),
        migrations.AddIndex(
            model_name='orgperson',
            index=models.Index(fields=['deleted', 'org_id', 'person_id'], name='org_person_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['name'], name='api_meetupt_name_470fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['crew_template_id'], name='api_meetupt_crew_te_503e65_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['subject_id'], name='api_meetupt_subject_64766e_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['deleted'], name='api_meetupt_deleted_736280_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['work_in_progress'], name='api_meetupt_work_in_b2bb44_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['max_minutes'], name='api_meetupt_max_min_177a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='meetupspot',
            index=models.Index(fields=['deleted', 'name', 'spot_type_id', 'facility_id'], name='meetup_spot_idx'),
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['deleted', 'start_at', 'name'], name='api_meetup_deleted_97e3df_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['name', 'org_id', 'deleted'], name='facility_idx'),
        ),
    ]
