# Generated by Django 4.2.2 on 2023-10-17 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Meetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("name", models.CharField(max_length=64)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MeetupRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=24)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MeetupSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MeetupSpotInMeetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrgPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=48)),
                ("first_name", models.CharField(max_length=48)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("value", models.CharField(max_length=32)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.person",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "org",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMeetupSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "meetup_spot",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.meetupspot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpotType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["deleted", "name"], name="spot_type_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48)),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["deleted", "name"],
                        name="api_profess_deleted_0b9d6b_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["deleted", "last_name", "first_name"], name="person_idx"
            ),
        ),
        migrations.AddField(
            model_name="orgperson",
            name="org",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.org",
            ),
        ),
        migrations.AddField(
            model_name="orgperson",
            name="person",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.person",
            ),
        ),
        migrations.AddIndex(
            model_name="org",
            index=models.Index(fields=["deleted", "name"], name="org_idx"),
        ),
        migrations.AddField(
            model_name="meetupspotinmeetup",
            name="meetup",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.meetup",
            ),
        ),
        migrations.AddField(
            model_name="meetupspotinmeetup",
            name="meetup_spot",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.meetupspot",
            ),
        ),
        migrations.AddField(
            model_name="meetupspot",
            name="facility",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.facility",
            ),
        ),
        migrations.AddField(
            model_name="meetupspot",
            name="spot_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.spottype",
            ),
        ),
        migrations.AddIndex(
            model_name="meetuprole",
            index=models.Index(
                fields=["deleted", "name"], name="api_meetupr_deleted_814e7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetup",
            index=models.Index(
                fields=["deleted", "start_at", "name"],
                name="api_meetup_deleted_97e3df_idx",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.org"
            ),
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=models.Index(
                fields=["deleted", "user_id", "name"], name="user_preference_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userperson",
            index=models.Index(
                fields=["deleted", "user_id", "person_id"], name="user_person_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userorg",
            index=models.Index(
                fields=["deleted", "user_id", "org_id"], name="user_org_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermeetupspot",
            index=models.Index(
                fields=["deleted", "user_id", "meetup_spot_id"],
                name="user_meetup_spot_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orgperson",
            index=models.Index(
                fields=["deleted", "org_id", "person_id"], name="org_person_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetupspotinmeetup",
            index=models.Index(
                fields=["deleted", "meetup_id", "meetup_spot_id"],
                name="api_meetups_deleted_25651d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetupspot",
            index=models.Index(
                fields=["deleted", "name", "spot_type_id", "facility_id"],
                name="meetup_spot_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["name", "org_id", "deleted"], name="facility_idx"
            ),
        ),
    ]
