# Generated by Django 4.2.5 on 2024-08-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetupRole',
        ),
        migrations.RemoveField(
            model_name='meetupspotinmeetup',
            name='meetup',
        ),
        migrations.RemoveField(
            model_name='meetupspotinmeetup',
            name='meetup_spot',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='Meetup',
        ),
        migrations.DeleteModel(
            name='MeetupSpotInMeetup',
        ),
    ]
