# Generated by Django 4.2.2 on 2023-09-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="OrgPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.IntegerField()),
                ("person_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("person_id", models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["last_name", "first_name"], name="person_idx"),
        ),
    ]
