# Generated by Django 4.2.18 on 2025-01-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_focus_description_alter_meetup_meetup_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='api_village_name_23e2f8_idx')],
            },
        ),
    ]
