# Generated by Django 4.2.2 on 2023-09-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_org_orgperson_userperson_person_person_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="meetup",
            index=models.Index(
                fields=["start_at"], name="api_meetup_start_a_377ec9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetuprole",
            index=models.Index(fields=["name"], name="api_meetupr_name_f265ad_idx"),
        ),
        migrations.AddIndex(
            model_name="org",
            index=models.Index(fields=["name"], name="org_idx"),
        ),
        migrations.AddIndex(
            model_name="orgperson",
            index=models.Index(fields=["org_id", "person_id"], name="org_person_idx"),
        ),
        migrations.AddIndex(
            model_name="profession",
            index=models.Index(fields=["name"], name="api_profess_name_9379e1_idx"),
        ),
        migrations.AddIndex(
            model_name="showup",
            index=models.Index(
                fields=["person_id", "meetup_role_id"],
                name="api_showup_person__d75ab0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userperson",
            index=models.Index(fields=["user_id", "person_id"], name="user_person_idx"),
        ),
    ]
