# Generated by Django 4.2.5 on 2024-08-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_meetuprole_remove_meetupspotinmeetup_meetup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('prereqs', models.ManyToManyField(null=True, to='api.meetuptemplate')),
            ],
        ),
    ]
