# Generated by Django 4.2.5 on 2024-08-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meetuptemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='meetuptemplate',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['name'], name='api_meetupt_name_470fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['deleted'], name='api_meetupt_deleted_736280_idx'),
        ),
    ]
