# Generated by Django 4.2.18 on 2025-01-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['description'], name='api_village_descrip_ee53c0_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['deleted'], name='api_village_deleted_678a3d_idx'),
        ),
    ]
