# Generated by Django 4.2.5 on 2023-09-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_meetup_api_meetup_start_a_377ec9_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("org_id", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user_id", "org_id"], name="user_org_idx")
                ],
            },
        ),
    ]
