# Generated by Django 4.2.5 on 2023-09-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userorg"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("name", models.CharField(max_length=32)),
                ("value", models.CharField(max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user_id", "name"], name="user_preference_idx")
                ],
            },
        ),
    ]
