# Generated by Django 4.2.18 on 2025-02-03 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_village_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_modality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.learningmodality')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.topic')),
            ],
        ),
        migrations.AddIndex(
            model_name='learningmodality',
            index=models.Index(fields=['name', 'deleted'], name='api_learnin_name_87abdf_idx'),
        ),
        migrations.AddIndex(
            model_name='preferredmodality',
            index=models.Index(fields=['person_id', 'topic_id', 'learning_modality_id'], name='api_preferr_person__483f56_idx'),
        ),
    ]
