# Generated by Django 4.2.5 on 2024-09-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_person_user_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['deleted', 'name'], name='api_subject_deleted_5cea12_idx')],
            },
        ),
    ]
