# Generated by Django 4.2.18 on 2025-02-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_learningmodality_preferredmodality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prereqdetail',
            old_name='template',
            new_name='meetup_template',
        ),
        migrations.RenameField(
            model_name='prereqset',
            old_name='required_by',
            new_name='meetup_template',
        ),
        migrations.AddField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['created_at'], name='api_userses_created_a9e3ba_idx'),
        ),
    ]
