# Generated by Django 4.2.18 on 2025-02-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_template_prereqdetail_meetup_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredmodality',
            name='learning_modality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.learningmodality'),
        ),
    ]
