# Generated by Django 4.2.5 on 2023-09-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_facility_facility_idx_facility_org_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MeetUp",
        ),
        migrations.DeleteModel(
            name="MeetupRole",
        ),
        migrations.DeleteModel(
            name="OrgPerson",
        ),
        migrations.DeleteModel(
            name="Profession",
        ),
        migrations.DeleteModel(
            name="ShowUp",
        ),
        migrations.DeleteModel(
            name="UserPerson",
        ),
    ]
