# Generated by Django 4.2.5 on 2024-09-03 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetuptemplate',
            name='prereqs',
        ),
        migrations.CreateModel(
            name='PrereqSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_numerator', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('required_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetuptemplate')),
            ],
        ),
    ]
