# Generated by Django 4.2.5 on 2023-09-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_delete_meetup_delete_meetuprole_delete_orgperson_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("person_id", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id", "person_id"], name="user_person_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Showup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_id", models.IntegerField()),
                ("meetup_role_id", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["person_id", "meetup_role_id"],
                        name="api_showup_person__d75ab0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="api_profess_name_9379e1_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="OrgPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.IntegerField()),
                ("person_id", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["org_id", "person_id"], name="org_person_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MeetupRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=24)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="api_meetupr_name_f265ad_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Meetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("duration", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start_at"], name="api_meetup_start_a_377ec9_idx"
                    )
                ],
            },
        ),
    ]
