# Generated by Django 4.2.18 on 2025-02-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_org_authority_name_org_city_org_cmaname_org_cmauid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
