# Generated by Django 4.2.5 on 2024-09-04 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_meetuptemplate_prereqs_prereqset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrereqDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('mandatory', models.BooleanField(default=True)),
                ('prereq_set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.prereqset')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetuptemplate')),
            ],
        ),
    ]
