# Generated by Django 4.2.18 on 2025-02-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_org_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='minute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
