# Generated by Django 4.2.18 on 2025-02-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_meetup_hour_meetup_minute_alter_meetup_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='duration',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='minute',
            field=models.IntegerField(default=0),
        ),
    ]
