# Generated by Django 4.2.2 on 2023-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_spottype_meetupspot"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="meetupspot",
            name="meetup_spot_idx",
        ),
        migrations.AddField(
            model_name="meetupspot",
            name="facility_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="meetupspot",
            index=models.Index(
                fields=["name", "spot_type_id", "facility_id"], name="meetup_spot_idx"
            ),
        ),
    ]
