# Generated by Django 4.2.5 on 2024-09-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
