# Generated by Django 4.2.18 on 2025-02-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_meetup_duration_alter_meetup_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='dom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetup',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetup',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
