# Generated by Django 4.2.5 on 2024-09-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_crewtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('crew_template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.crewtemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['crew_template_id', 'deleted'], name='api_templat_crew_te_f196e1_idx'), models.Index(fields=['name', 'deleted'], name='api_templat_name_ab4bb8_idx')],
            },
        ),
    ]
