# Generated by Django 4.2.5 on 2024-09-05 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_templaterole'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuptemplate',
            name='crew_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.crewtemplate'),
        ),
        migrations.AddIndex(
            model_name='crewtemplate',
            index=models.Index(fields=['name', 'deleted'], name='api_crewtem_name_95e4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['crew_template_id'], name='api_meetupt_crew_te_503e65_idx'),
        ),
    ]
