# Generated by Django 4.2.18 on 2025-02-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_meetup_dom_meetup_month_meetup_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='start_at_unix',
            field=models.IntegerField(null=True),
        ),
    ]
