# Generated by Django 4.2.5 on 2024-09-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_meetuptemplate_crew_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templaterole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
