# Generated by Django 4.2.18 on 2025-02-12 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_meetup_start_at_unix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='crew',
        ),
        migrations.AddField(
            model_name='crew',
            name='meetup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetup'),
        ),
    ]
