# Generated by Django 4.2.18 on 2025-02-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_meetup_crew_crew_meetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.topic'),
        ),
    ]
