# Generated by Django 4.2.5 on 2024-09-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_templaterole_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='templaterole',
            name='max_count',
            field=models.IntegerField(default=0),
        ),
    ]
