# Generated by Django 4.2.5 on 2024-09-06 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_templaterole_max_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuptemplate',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.facility'),
        ),
        migrations.AddField(
            model_name='meetuptemplate',
            name='meetup_spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetupspot'),
        ),
        migrations.AddField(
            model_name='meetuptemplate',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.org'),
        ),
    ]
