# Generated by Django 4.2.18 on 2025-02-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_meetup_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil_count', models.IntegerField(default=0)),
                ('guru_count', models.IntegerField(default=0)),
                ('daily_meetup_interval_length', models.IntegerField(default=0)),
                ('intermeetup_transition', models.IntegerField(default=0)),
                ('max_meetups_per_guru_per_day', models.IntegerField(default=0)),
                ('total_guru_minutes_per_day', models.IntegerField(default=0)),
                ('max_pupil_meetups_per_day', models.IntegerField(default=0)),
                ('minimum_pupil_meetups_per_day', models.IntegerField(default=0)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.org')),
            ],
        ),
    ]
