# Generated by Django 4.2.18 on 2025-02-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_meetupcalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupSpaceCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_persons', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
