# Generated by Django 4.2.5 on 2024-09-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuptemplate',
            name='focus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.focus'),
        ),
        migrations.AddField(
            model_name='meetuptemplate',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.subject'),
        ),
        migrations.AddField(
            model_name='meetuptemplate',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.topic'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['focus_id'], name='api_meetupt_focus_i_baf35d_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['subject_id'], name='api_meetupt_subject_64766e_idx'),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['topic_id'], name='api_meetupt_topic_i_48be19_idx'),
        ),
    ]
