# Generated by Django 4.2.18 on 2025-02-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_meetupspacecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupspacecount',
            name='meetup_calculation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetupcalculation'),
            preserve_default=False,
        ),
    ]
