# Generated by Django 4.2.5 on 2024-09-07 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_meetuptemplate_focus_meetuptemplate_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('deleted', models.BooleanField(default=False)),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.crew')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.facility')),
                ('meetup_spot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetupspot')),
                ('meetup_template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetuptemplate')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.org')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
            ],
            options={
                'indexes': [models.Index(fields=['person_id'], name='api_signup_person__02990f_idx'), models.Index(fields=['meetup_id'], name='api_signup_meetup__0d7cf3_idx'), models.Index(fields=['created_at'], name='api_signup_created_3b0745_idx'), models.Index(fields=['deleted'], name='api_signup_deleted_6c2376_idx'), models.Index(fields=['created_by'], name='api_signup_created_604e78_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='meetup',
            index=models.Index(fields=['deleted', 'start_at', 'name'], name='api_meetup_deleted_97e3df_idx'),
        ),
    ]
