# Generated by Django 4.2.18 on 2025-02-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_meetupspacecount_meetup_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupcalculation',
            name='faclity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.facility'),
        ),
    ]
