# Generated by Django 4.2.5 on 2024-09-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_meetup_signup_meetup_api_meetup_deleted_97e3df_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuptemplate',
            name='work_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='meetuptemplate',
            index=models.Index(fields=['work_in_progress'], name='api_meetupt_work_in_b2bb44_idx'),
        ),
    ]
