# Generated by Django 4.2.18 on 2025-02-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_meetupcalculation_faclity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetupcalculation',
            old_name='faclity',
            new_name='facility',
        ),
    ]
