# Generated by Django 4.2.5 on 2024-09-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_meetuptemplate_work_in_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='meetuptemplate',
            name='api_meetupt_topic_i_48be19_idx',
        ),
        migrations.RemoveField(
            model_name='meetuptemplate',
            name='topic',
        ),
        migrations.AddField(
            model_name='templatetopic',
            name='meetup_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.meetuptemplate'),
        ),
        migrations.AddIndex(
            model_name='templatetopic',
            index=models.Index(fields=['meetup_template_id', 'deleted'], name='api_templat_meetup__dcfe07_idx'),
        ),
        migrations.AddIndex(
            model_name='templatetopic',
            index=models.Index(fields=['meetup_template_id'], name='api_templat_meetup__2d17e1_idx'),
        ),
    ]
