# Generated by Django 4.2.5 on 2024-09-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_templatetopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetopic',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.topic'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='templatetopic',
            index=models.Index(fields=['topic_id', 'deleted'], name='api_templat_topic_i_8f7146_idx'),
        ),
        migrations.AddIndex(
            model_name='templatetopic',
            index=models.Index(fields=['meetup_template_id', 'topic_id', 'deleted'], name='api_templat_meetup__7cc831_idx'),
        ),
        migrations.AddIndex(
            model_name='templatetopic',
            index=models.Index(fields=['topic_id'], name='api_templat_topic_i_a403d9_idx'),
        ),
    ]
