# Generated by Django 4.2.18 on 2025-02-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_meetupcalculation_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['deleted', 'type'], name='api_testimo_deleted_ce4e2b_idx')],
            },
        ),
    ]
