# Generated by Django 4.2.18 on 2025-02-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
