# Generated by Django 4.2.18 on 2025-02-24 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_testimony_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.topic'),
        ),
        migrations.CreateModel(
            name='FrequentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['deleted'], name='api_frequen_deleted_c672cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='FocalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.signup')),
            ],
        ),
        migrations.CreateModel(
            name='FocalArtifactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'deleted'], name='api_focalar_name_fed11d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FocalArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('focal_artifact_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.focalartifacttype')),
                ('focal_result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.focalresult')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('frequent_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.frequentquestion')),
            ],
            options={
                'indexes': [models.Index(fields=['deleted'], name='api_frequen_deleted_a1b86b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='focalresult',
            index=models.Index(fields=['deleted'], name='api_focalre_deleted_43b975_idx'),
        ),
        migrations.AddIndex(
            model_name='focalartifact',
            index=models.Index(fields=['name', 'deleted'], name='api_focalar_name_11e5fa_idx'),
        ),
    ]
