# Generated by Django 4.2.18 on 2025-02-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_focus_topic_frequentquestion_focalresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentquestion',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
